[metadata]
format.version = "1.1"

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
docker = { id = "com.bmuschko.docker-remote-api", version = "9.4.0" }
edc-build = { id = "org.eclipse.edc.edc-build", version = "0.8.1" }